"""fix cardio duration

Revision ID: 415f529a408c
Revises: 2f362bb9bba8
Create Date: 2025-05-22 10:53:28.535612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415f529a408c'
down_revision = '2f362bb9bba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('streak_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('streak_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
